// Writes src/components/unloaded-ant-art.ts from the supplied brand files.
// Run with `pnpm --filter @bandwise/web brand:ant` (Node 22 strips the types).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { inlineUnloadedAnt } from "../src/lib/unloaded-ant.ts";

const root = fileURLToPath(new URL("..", import.meta.url));
const read = (theme: "light" | "dark") =>
  inlineUnloadedAnt(readFileSync(`${root}../../brand/unloaded/bandwise-ant-unloaded-A-r4-right-${theme}.svg`, "utf8"));

const out = `// Generated by scripts/brand-ant.ts from brand/unloaded/bandwise-ant-unloaded-A-r4-right-{light,dark}.svg.
// Do not edit. The paths, transforms and fills are the supplied ones (see src/lib/unloaded-ant.ts).

export const UNLOADED_ANT_LIGHT = ${JSON.stringify(read("light"))};

export const UNLOADED_ANT_DARK = ${JSON.stringify(read("dark"))};
`;
writeFileSync(`${root}src/components/unloaded-ant-art.ts`, out);
