// Builds the public bandwise-kit repository tree from this monorepo. Run it for every kit release;
// docs/runbooks/kit-release.md has the steps. It writes only into the output folder and fails
// when the scanner finds anything private in what it wrote.

import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { TEMPLATES } from "@bandwise/templates";
import { kitReadme, packageReadme, type ReadmeTemplate } from "./readme.js";
import { type RewriteCounts, dropTests, rewriteComments, rewriteTestTitles } from "./rewrite.js";
import { DEFAULT_INTERNAL_DOC_NAMES, type ScanFinding, scanTree } from "./scan.js";

export const KIT_VERSION = "0.2.1";
export const KIT_REPO = "glacer06/bandwise-kit";
export const KIT_HOMEPAGE = "https://docs.bandwise.dev";

/** Published kit packages, in dependency order. The release workflow publishes in this order. */
export const PUBLISHED_PACKAGES = ["core", "system-one-client", "templates", "cli"] as const;

/** The monorepo root, three levels above this file (scripts/kit-export/src). */
export const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");
const OVERLAY_DIR = resolve(dirname(fileURLToPath(import.meta.url)), "../overlay");

/** Monorepo folders copied into the kit. */
const SOURCES = [
  "packages/core",
  "packages/system-one-client",
  "packages/templates",
  "packages/cli",
  "plugins/claude-code/skills/find-decisions",
  // The agent pack as Claude Code hook sets, with example states. The CLI tests run them.
  ".bandwise",
] as const;

/** Files inside SOURCES that stay private, with the reason. */
export const EXCLUDED: ReadonlyArray<{ re: RegExp; why: string }> = [
  { re: /^packages\/core\/openapi\.json$/, why: "the management API document is generated by the closed console" },
  { re: /^packages\/cli\/src\/(local|live)\/__fixtures__\//, why: "deliberate lint violations checked by the monorepo's boundary test" },
  { re: /^packages\/cli\/src\/remote\/replies\.contract\.test\.ts$/, why: "checks the fake server replies against the management API document, which stays private" },
  { re: /^packages\/system-one-client\/contract\//, why: "snapshots of TypeSafe's own docs for the private contract watch" },
  { re: /^packages\/system-one-client\/src\/contract\.ts$/, why: "loads the contract snapshots, which stay private" },
  { re: /^packages\/system-one-client\/src\/fixture\/fixtures\.contract\.test\.ts$/, why: "checks fixtures against the private contract snapshot" },
];

/** Files copied to a different place in the kit. */
const MOVES: Record<string, string> = {
  ".claude/skills/bandwise-builder/templates/question-set.example.json": "examples/email-triage.spec.json",
  "packages/cli/examples/email-triage.state.json": "examples/email-triage.state.json",
  "packages/config/vitest/index.js": "packages/config/vitest/index.js",
  "packages/config/vitest/index.d.ts": "packages/config/vitest/index.d.ts",
};

/** Text replaced in every copied file. */
const GLOBAL_REPLACEMENTS: ReadonlyArray<{ find: string; replace: string; why: string }> = [
  {
    find: ".claude/skills/bandwise-builder/templates/question-set.example.json",
    replace: "examples/email-triage.spec.json",
    why: "the example spec moves out of the private skill folder",
  },
  { find: "@acme.com", replace: "@example.com", why: "example addresses use a reserved example domain" },
];

interface Patch {
  file: string;
  find: string;
  replace: string;
  why: string;
}

/** Exact edits to single kit files. Each must match exactly once, so drift fails the export. */
const PATCHES: readonly Patch[] = [
  {
    file: "packages/cli/src/local/main.test.ts",
    find: 'at("../examples/email-triage.state.json")',
    replace: 'at("../../../examples/email-triage.state.json")',
    why: "the example state moves to examples/ at the kit root",
  },
  {
    file: "packages/cli/src/live/live.test.ts",
    find: 'at("../../examples/email-triage.state.json")',
    replace: 'at("../../../../examples/email-triage.state.json")',
    why: "the example state moves to examples/ at the kit root",
  },
  {
    file: "packages/system-one-client/src/index.ts",
    find: 'export { CONTRACT_SNAPSHOT_DIR, CONTRACT_SOURCES, type ContractSource, loadContractSnapshots } from "./contract.js";\n',
    replace: "",
    why: "the contract snapshot loader stays private",
  },
  {
    file: "packages/system-one-client/src/fixture/fixture-transport.test.ts",
    find: 'new URL("../../contract/", import.meta.url).pathname',
    replace: 'new URL("../../fixtures/specs/", import.meta.url).pathname',
    why: "a folder of non-fixture JSON for the bad-fixture test, now that contract/ stays private",
  },
  {
    file: "packages/core/src/contracts/operations.ts",
    find: "or redacted to full (data-model.md).",
    replace: "or redacted to full.",
    why: "an approval condition text pointed at an internal doc",
  },
  ...(
    [
      ["typesafe", "(HTTP 503 after SDK retries, ADR-012)", "(HTTP 503 after SDK retries)"],
      ["openrouter", "(HTTP 503, no available provider, ADR-012)", "(HTTP 503, no available provider)"],
      ["vercel", "(HTTP 503, ADR-012 and ADR-013)", "(HTTP 503)"],
    ] as const
  ).map(([provider, find, replace]) => ({
    file: `packages/system-one-client/fixtures/${provider}/outage-503.json`,
    find,
    replace,
    why: "the outage fixture's example text named internal design records",
  })),
];

/**
 * Comment and test-title phrases the generic rewrite would leave awkward. Applied to every code
 * file before the comment rewrite; each must match at least once, so drift fails the export.
 */
const PHRASES: ReadonlyArray<{ find: string; replace: string }> = [
  { find: "the rounding savings-model.md fixes for", replace: "the rounding used for" },
  { find: "// ADR-012: the outage rows of the effective-action table.", replace: "// The outage rows of the effective-action table." },
  { find: "`review` since ADR-012 Amendment 1: an", replace: "`review`: an" },
  { find: "USD numbers, exactly as savings-model.md defines them.", replace: "USD numbers." },
  { find: "recorded before ADR-011", replace: "recorded before provider routes existed" },
  { find: "Absent on events from before ADR-011,", replace: "Absent on events from before provider routes existed," },
  { find: "// ADR-011 and ADR-013: System One through", replace: "// System One through" },
  { find: " ADR-008 adds ModelCatalog. ADR-011\n// adds the System One provider to keys, calls, the catalog and run settings.", replace: "" },
  { find: "matches architecture.md and maps every run source", replace: "has the latency budgets and maps every run source" },
  { find: " The management-api.md row needs the same change.", replace: "" },
  {
    find: "data-model.md makes a storageMode move to a less private mode a\n  // PII change",
    replace: "a storageMode move to a less private mode is a\n  // PII change",
  },
  { find: "effectiveness-loop.md section 9 makes samplePct above 0.25 high", replace: "samplePct above 0.25 is high" },
  {
    find: "\n// The other management commands over /api/v1\n// land in Phase 3 (headless-and-agents.md).",
    replace: "\n// Other management commands over /api/v1 land in a later release.",
  },
  {
    find: "// @bandwise/cli (bin bandwise): management commands over /api/v1 (Phase 3), plus `run --local`.",
    replace: "// @bandwise/cli (bin bandwise): run a spec on a state locally, on fixtures or live with your own key.",
  },
];

/** Tests that compare code with internal design docs. They are dropped from the kit copy. */
const DROPPED_TESTS: Record<string, readonly string[]> = {
  "packages/core/src/contracts/events.test.ts": ["matches every type in the events.md catalog tables"],
  "packages/core/src/contracts/errors.test.ts": ["matches the api.md code table: status, code and retryable"],
  "packages/core/src/contracts/operations.test.ts": ["catalog matches management-api.md"],
};

const PACKAGE_DESCRIPTIONS: Record<string, string> = {
  core: "Bandwise question set spec format, lints and run engine. Pure TypeScript, no I/O.",
  "system-one-client":
    "Transports for Bandwise runs: System One models through TypeSafe, OpenRouter or the Vercel AI Gateway with your own key, or recorded fixtures with no network.",
  templates: "The Bandwise template pack: question set specs with example states and a borderline case per question.",
  cli: "The bandwise command. `bandwise run --local` runs a question set spec on a state with no network and no key; `bandwise run --live` and `bandwise hook` run it against the real model with your own key.",
};

const KEYWORDS = ["bandwise", "system-one", "jev", "typesafe", "llm", "classification", "decisions"];

export interface ExportOptions {
  outDir: string;
  repoRoot?: string;
  /** Run `pnpm install --lockfile-only` in the output to write pnpm-lock.yaml. */
  lockfile?: boolean;
}

export interface ExportReport {
  outDir: string;
  files: string[];
  excluded: Array<{ file: string; why: string }>;
  moved: Record<string, string>;
  replacements: Record<string, number>;
  patches: Array<{ file: string; why: string }>;
  droppedTests: Array<{ file: string; title: string }>;
  rewrites: RewriteCounts;
  rewrittenFiles: string[];
  findings: ScanFinding[];
}

type Json = Record<string, unknown>;

const toPosix = (p: string): string => p.split(sep).join("/");

function gitFiles(repoRoot: string, paths: readonly string[]): string[] {
  const out = execFileSync("git", ["ls-files", "-z", "--cached", "--others", "--exclude-standard", "--", ...paths], {
    cwd: repoRoot,
    encoding: "utf8",
    maxBuffer: 64 * 1024 * 1024,
  });
  return [...new Set(out.split("\0").filter((f) => f !== ""))].filter((f) => existsSync(join(repoRoot, f))).sort();
}

function walkFiles(dir: string, base = dir): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir).sort()) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walkFiles(full, base));
    else out.push(toPosix(relative(base, full)));
  }
  return out;
}

/** Empty the output folder, keeping .git and pnpm-lock.yaml. Refuses folders that look wrong. */
function prepareOutDir(outDir: string, repoRoot: string): void {
  const out = resolve(outDir);
  const root = resolve(repoRoot);
  if (out === root || root.startsWith(`${out}${sep}`)) throw new Error(`kit export: refusing to write into ${out}, which holds the monorepo`);
  if (out.startsWith(`${root}${sep}`) && !out.startsWith(`${join(root, "dist-kit")}`)) {
    throw new Error(`kit export: inside the monorepo the output must be under dist-kit/, not ${out}`);
  }
  if (!existsSync(out)) {
    mkdirSync(out, { recursive: true });
    return;
  }
  const entries = readdirSync(out);
  if (entries.length === 0) return;
  const pkgPath = join(out, "package.json");
  const isKit = existsSync(pkgPath) && (JSON.parse(readFileSync(pkgPath, "utf8")) as Json)["name"] === "bandwise-kit";
  if (!isKit && !entries.includes(".git")) {
    throw new Error(`kit export: ${out} is not empty and is not a bandwise-kit checkout; pick an empty folder`);
  }
  for (const entry of entries) {
    if (entry === ".git" || entry === "pnpm-lock.yaml") continue;
    rmSync(join(out, entry), { recursive: true, force: true });
  }
}

/** The monorepo's pnpm catalog, name to version. */
export function readCatalog(workspaceYaml: string): Record<string, string> {
  const catalog: Record<string, string> = {};
  let inside = false;
  for (const raw of workspaceYaml.split("\n")) {
    if (/^catalog:\s*$/.test(raw)) {
      inside = true;
      continue;
    }
    if (!inside) continue;
    if (/^\S/.test(raw)) break;
    const line = raw.trim();
    if (line === "" || line.startsWith("#")) continue;
    const m = /^"?([^":]+)"?:\s*(\S+)\s*$/.exec(line);
    if (m !== null) catalog[m[1] as string] = m[2] as string;
  }
  return catalog;
}

function depsOf(manifest: Json): Record<string, string> {
  const all: Record<string, string> = {};
  for (const field of ["dependencies", "devDependencies", "peerDependencies"]) {
    const deps = manifest[field] as Record<string, string> | undefined;
    if (deps !== undefined) Object.assign(all, deps);
  }
  return all;
}

/** The kit version of a package manifest. */
export function kitManifest(source: Json, dir: string, version: string): Json {
  const m: Json = structuredClone(source);
  delete m["private"];
  m["version"] = version;
  const description = PACKAGE_DESCRIPTIONS[dir];
  if (description === undefined) throw new Error(`kit export: no description for packages/${dir}`);
  m["description"] = description;
  m["license"] = "Apache-2.0";
  m["keywords"] = KEYWORDS;
  m["homepage"] = KIT_HOMEPAGE;
  m["repository"] = { type: "git", url: `git+https://github.com/${KIT_REPO}.git`, directory: `packages/${dir}` };
  m["bugs"] = { url: `https://github.com/${KIT_REPO}/issues` };
  m["engines"] = { node: ">=22" };
  m["publishConfig"] = { access: "public", provenance: true };

  const exports = m["exports"] as Json | undefined;
  if (exports !== undefined) delete exports["./openapi.json"];
  const files = m["files"] as string[] | undefined;
  if (files !== undefined) m["files"] = files.filter((f) => f !== "openapi.json" && f !== "contract");

  if (dir === "cli") {
    // In the kit the CLI's only command is local mode, so core and the fixture transport are
    // real dependencies. As optional peers, `npx @bandwise/cli` would not install them.
    const peers = (m["peerDependencies"] ?? {}) as Record<string, string>;
    const deps = (m["dependencies"] ?? {}) as Record<string, string>;
    const dev = (m["devDependencies"] ?? {}) as Record<string, string>;
    for (const name of Object.keys(peers)) deps[name] = peers[name] as string;
    m["dependencies"] = Object.fromEntries(Object.entries(deps).sort(([a], [b]) => a.localeCompare(b)));
    m["devDependencies"] = Object.fromEntries(Object.entries(dev).filter(([name]) => !(name in peers)));
    delete m["peerDependencies"];
    delete m["peerDependenciesMeta"];
  }

  // Keep a stable, readable key order.
  const order = [
    "name",
    "version",
    "description",
    "keywords",
    "homepage",
    "bugs",
    "license",
    "repository",
    "type",
    "bin",
    "exports",
    "files",
    "engines",
    "publishConfig",
    "scripts",
    "dependencies",
    "peerDependencies",
    "peerDependenciesMeta",
    "devDependencies",
  ];
  const sorted: Json = {};
  for (const k of order) if (k in m) sorted[k] = m[k];
  for (const k of Object.keys(m)) if (!(k in sorted)) sorted[k] = m[k];
  return sorted;
}

function rootManifest(): Json {
  return {
    name: "bandwise-kit",
    private: true,
    description: "The open part of Bandwise: the question set spec format, the local runner and CLI, the template pack and the find-decisions skill.",
    license: "Apache-2.0",
    repository: { type: "git", url: `git+https://github.com/${KIT_REPO}.git` },
    type: "module",
    packageManager: "pnpm@10.33.0",
    engines: { node: ">=22.13.0" },
    scripts: {
      build: "pnpm -r run build",
      lint: "pnpm -r run lint",
      typecheck: "pnpm -r run typecheck",
      test: "pnpm -r run test",
      bandwise: "node packages/cli/dist/bin.js",
    },
  };
}

function workspaceYaml(catalog: Record<string, string>): string {
  const lines = Object.keys(catalog)
    .sort()
    .map((name) => `  ${/^[a-z0-9-]+$/.test(name) ? name : JSON.stringify(name)}: ${catalog[name]}`);
  return [
    "packages:",
    "  - packages/*",
    "",
    "# Shared tool and library versions. Packages reference them as \"catalog:\".",
    "# pnpm pack writes the real versions into every published package.json.",
    "catalog:",
    ...lines,
    "",
    "# esbuild ships prebuilt binaries, so its postinstall is not needed.",
    "ignoredBuiltDependencies:",
    "  - esbuild",
    "",
  ].join("\n");
}

/** Names of the monorepo's internal design docs, which the kit must never mention. */
export function internalDocNames(repoRoot: string): string[] {
  const refs = join(repoRoot, ".claude/skills/bandwise-builder/references");
  const names = new Set<string>(DEFAULT_INTERNAL_DOC_NAMES);
  if (existsSync(refs)) {
    for (const f of walkFiles(refs)) names.add(f.split("/").pop() as string);
  }
  for (const f of existsSync(join(repoRoot, "docs")) ? walkFiles(join(repoRoot, "docs")) : []) {
    const base = f.split("/").pop() as string;
    // Plans, ADRs, runbooks and the backlog. A generic README.md stays allowed.
    if (base.endsWith(".md") && base !== "README.md") names.add(base);
  }
  return [...names].sort();
}

const isCode = (f: string): boolean => /\.(ts|tsx|js|mjs|cjs)$/.test(f);
const isTest = (f: string): boolean => /\.test\.tsx?$/.test(f);

function writeFile(outDir: string, rel: string, text: string): void {
  const full = join(outDir, rel);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, text);
}

/** Write the kit tree into `outDir`, then scan it. The report lists every change the export made. */
export function exportKit(options: ExportOptions): ExportReport {
  const repoRoot = resolve(options.repoRoot ?? REPO_ROOT);
  const outDir = resolve(options.outDir);
  prepareOutDir(outDir, repoRoot);
  const docNames = internalDocNames(repoRoot);

  const report: ExportReport = {
    outDir,
    files: [],
    excluded: [],
    moved: {},
    replacements: {},
    patches: [],
    droppedTests: [],
    rewrites: {},
    rewrittenFiles: [],
    findings: [],
  };
  const written = new Map<string, string>();
  const emit = (rel: string, text: string): void => {
    if (written.has(rel)) throw new Error(`kit export: ${rel} written twice`);
    written.set(rel, text);
  };

  const catalogSource = readCatalog(readFileSync(join(repoRoot, "pnpm-workspace.yaml"), "utf8"));
  const usedPatches = new Set<Patch>();
  const usedPhrases = new Set<(typeof PHRASES)[number]>();

  for (const src of gitFiles(repoRoot, [...SOURCES, ...Object.keys(MOVES)])) {
    const excluded = EXCLUDED.find((e) => e.re.test(src));
    if (excluded !== undefined) {
      report.excluded.push({ file: src, why: excluded.why });
      continue;
    }
    const dst = MOVES[src] ?? src;
    if (dst !== src) report.moved[src] = dst;
    let text = readFileSync(join(repoRoot, src), "utf8");

    const pkgMatch = /^packages\/([^/]+)\/package\.json$/.exec(src);
    if (pkgMatch !== null) {
      const dir = pkgMatch[1] as string;
      emit(dst, `${JSON.stringify(kitManifest(JSON.parse(text) as Json, dir, KIT_VERSION), null, 2)}\n`);
      continue;
    }

    for (const r of GLOBAL_REPLACEMENTS) {
      const count = text.split(r.find).length - 1;
      if (count > 0) {
        text = text.split(r.find).join(r.replace);
        report.replacements[r.find] = (report.replacements[r.find] ?? 0) + count;
      }
    }
    for (const p of PATCHES.filter((p) => p.file === src)) {
      const count = text.split(p.find).length - 1;
      if (count !== 1) throw new Error(`kit export: patch for ${src} matched ${count} times, expected 1 (${p.why})`);
      text = text.replace(p.find, () => p.replace);
      usedPatches.add(p);
      report.patches.push({ file: src, why: p.why });
    }
    if (isCode(src)) {
      for (const ph of PHRASES) {
        const count = text.split(ph.find).length - 1;
        if (count > 0) {
          text = text.split(ph.find).join(ph.replace);
          usedPhrases.add(ph);
        }
      }
    }
    const drop = DROPPED_TESTS[src];
    if (drop !== undefined) {
      const res = dropTests(text, src, drop);
      text = res.text;
      for (const title of res.dropped) report.droppedTests.push({ file: src, title });
    }
    if (isCode(src)) {
      const before = text;
      text = rewriteComments(text, src, { internalDocNames: docNames }, report.rewrites);
      if (isTest(src)) text = rewriteTestTitles(text, src, { internalDocNames: docNames }, report.rewrites);
      if (text !== before) report.rewrittenFiles.push(dst);
    }
    emit(dst, text);
  }
  const unusedPhrases = PHRASES.filter((p) => !usedPhrases.has(p));
  if (unusedPhrases.length > 0) throw new Error(`kit export: comment phrases no longer found: ${unusedPhrases.map((p) => JSON.stringify(p.find)).join(", ")}`);
  const unused = PATCHES.filter((p) => !usedPatches.has(p));
  if (unused.length > 0) throw new Error(`kit export: patches for missing files: ${unused.map((p) => p.file).join(", ")}`);
  for (const file of Object.keys(DROPPED_TESTS)) {
    if (!report.droppedTests.some((d) => d.file === file)) throw new Error(`kit export: ${file} was not exported`);
  }

  // Hand-written kit files: license, community docs, workflows and the kit's own config package.
  for (const rel of walkFiles(OVERLAY_DIR)) emit(rel, readFileSync(join(OVERLAY_DIR, rel), "utf8"));

  // The TypeScript base, from the monorepo's shared config. It lives in the config package, next
  // to library.json: Vite's tsconfig loader does not follow an extends that leaves a symlinked package.
  const base = JSON.parse(readFileSync(join(repoRoot, "packages/config/tsconfig/base.json"), "utf8")) as Json;
  base["display"] = "Bandwise kit base";
  emit("packages/config/tsconfig/base.json", `${JSON.stringify(base, null, 2)}\n`);

  // Per package: README and LICENSE, so npm shows them.
  const license = readFileSync(join(OVERLAY_DIR, "LICENSE"), "utf8");
  for (const dir of PUBLISHED_PACKAGES) {
    emit(`packages/${dir}/README.md`, packageReadme(dir, `@bandwise/${dir}`));
    emit(`packages/${dir}/LICENSE`, license);
  }

  // Root manifest, workspace and catalog of only what the kit uses.
  emit("package.json", `${JSON.stringify(rootManifest(), null, 2)}\n`);
  const kitNames = new Set<string>();
  const needed = new Set<string>();
  const manifests = [...written.entries()].filter(([f]) => /^packages\/[^/]+\/package\.json$/.test(f));
  for (const [, text] of manifests) kitNames.add((JSON.parse(text) as Json)["name"] as string);
  for (const [file, text] of manifests) {
    for (const [name, spec] of Object.entries(depsOf(JSON.parse(text) as Json))) {
      if (spec.startsWith("workspace:") && !kitNames.has(name)) throw new Error(`kit export: ${file} needs ${name}, which is not in the kit`);
      if (spec === "catalog:") needed.add(name);
      else if (spec.startsWith("catalog:")) throw new Error(`kit export: named catalogs are not supported (${file} ${name})`);
    }
  }
  const catalog: Record<string, string> = {};
  for (const name of needed) {
    const v = catalogSource[name];
    if (v === undefined) throw new Error(`kit export: ${name} is not in the monorepo catalog`);
    catalog[name] = v;
  }
  emit("pnpm-workspace.yaml", workspaceYaml(catalog));

  const templates: ReadmeTemplate[] = TEMPLATES.map((t) => ({
    id: t.id,
    title: t.title,
    job: t.job,
    questions: t.spec.stages.flatMap((s) => Object.keys(s.questions)),
  }));
  emit("README.md", kitReadme(templates));

  for (const [rel, text] of written) writeFile(outDir, rel, text);
  report.files = [...written.keys()].sort();

  if (options.lockfile === true) {
    execFileSync("pnpm", ["install", "--lockfile-only"], { cwd: outDir, stdio: "inherit" });
  }

  report.findings = scanTree(outDir, { internalDocNames: docNames });
  return report;
}
