-- Migration 0004: the Supabase performance advisor pass of 2026-09-28.
--
-- 1. A covering index, org_id first, for each of 23 foreign keys (lint 0001, unindexed_foreign_keys).
--    The runs index is partitioned, so Postgres builds it on every runs partition as well.
-- 2. The policy block from src/rls.ts, generation 2. Policies read app.org_id and app.user_id once
--    per statement instead of once per row (lint 0003, auth_rls_initplan), and no role holds two
--    permissive policies for the same table and command (lint 0006, multiple_permissive_policies).
--
-- Plain CREATE INDEX: migrations run in one transaction, which CONCURRENTLY cannot, and the tables
-- are empty.

CREATE INDEX "two_factors_user_id_idx" ON "two_factors" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "agent_tokens_user_id_idx" ON "agent_tokens" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "app_opportunities_org_id_app_id_idx" ON "app_opportunities" USING btree ("org_id","app_id");--> statement-breakpoint
CREATE INDEX "app_opportunities_org_id_set_id_idx" ON "app_opportunities" USING btree ("org_id","set_id");--> statement-breakpoint
CREATE INDEX "app_set_bindings_org_id_app_id_idx" ON "app_set_bindings" USING btree ("org_id","app_id");--> statement-breakpoint
CREATE INDEX "app_tokens_org_id_app_id_idx" ON "app_tokens" USING btree ("org_id","app_id");--> statement-breakpoint
CREATE INDEX "experiments_org_id_set_id_idx" ON "experiments" USING btree ("org_id","set_id");--> statement-breakpoint
CREATE INDEX "experiments_org_id_champion_version_id_idx" ON "experiments" USING btree ("org_id","champion_version_id");--> statement-breakpoint
CREATE INDEX "experiments_org_id_challenger_version_id_idx" ON "experiments" USING btree ("org_id","challenger_version_id");--> statement-breakpoint
CREATE INDEX "goals_org_id_project_id_idx" ON "goals" USING btree ("org_id","project_id");--> statement-breakpoint
CREATE INDEX "proposals_org_id_set_id_idx" ON "proposals" USING btree ("org_id","set_id");--> statement-breakpoint
CREATE INDEX "question_set_versions_org_id_set_id_idx" ON "question_set_versions" USING btree ("org_id","set_id");--> statement-breakpoint
CREATE INDEX "question_sets_org_id_project_id_idx" ON "question_sets" USING btree ("org_id","project_id");--> statement-breakpoint
CREATE INDEX "question_sets_org_id_goal_id_idx" ON "question_sets" USING btree ("org_id","goal_id");--> statement-breakpoint
CREATE INDEX "question_sets_org_id_draft_version_id_idx" ON "question_sets" USING btree ("org_id","draft_version_id");--> statement-breakpoint
CREATE INDEX "release_pointers_org_id_version_id_idx" ON "release_pointers" USING btree ("org_id","version_id");--> statement-breakpoint
CREATE INDEX "dataset_snapshots_org_id_dataset_id_idx" ON "dataset_snapshots" USING btree ("org_id","dataset_id");--> statement-breakpoint
CREATE INDEX "eval_runs_org_id_version_id_idx" ON "eval_runs" USING btree ("org_id","version_id");--> statement-breakpoint
CREATE INDEX "eval_runs_org_id_dataset_id_idx" ON "eval_runs" USING btree ("org_id","dataset_id");--> statement-breakpoint
CREATE INDEX "runs_org_id_version_id_idx" ON "runs" USING btree ("org_id","version_id");--> statement-breakpoint
CREATE INDEX "studio_examples_org_id_session_id_idx" ON "studio_examples" USING btree ("org_id","session_id");--> statement-breakpoint
CREATE INDEX "studio_sessions_org_id_goal_id_idx" ON "studio_sessions" USING btree ("org_id","goal_id");--> statement-breakpoint
CREATE INDEX "usage_daily_org_id_project_id_idx" ON "usage_daily" USING btree ("org_id","project_id");--> statement-breakpoint
-- bandwise:policy-block:start (generated by src/rls.ts; do not edit by hand)
DROP POLICY tenant_isolation ON "organizations";
--> statement-breakpoint
DROP POLICY user_memberships ON "organizations";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "memberships";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "invitations";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "org_system_one_keys";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "agent_tokens";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "org_webhook_secrets";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "apps";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "app_tokens";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "app_opportunities";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "app_set_bindings";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "projects";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "goals";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "question_sets";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "question_set_versions";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "release_pointers";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "release_events";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "experiments";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "proposals";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "runs";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "run_feedback";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "review_items";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "datasets";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "dataset_cases";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "dataset_snapshots";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "eval_runs";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "eval_case_results";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "studio_sessions";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "studio_examples";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "question_daily";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "usage_daily";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "billing_accounts";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "entitlement_overrides";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "usage_events";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "approval_requests";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "idempotency_keys";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "jobs";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "webhook_endpoints";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "plugin_configs";
--> statement-breakpoint
DROP POLICY user_lookup ON "memberships";
--> statement-breakpoint
DROP POLICY user_lookup ON "invitations";
--> statement-breakpoint
DROP POLICY tenant_read ON "price_books";
--> statement-breakpoint
DROP POLICY tenant_insert ON "price_books";
--> statement-breakpoint
DROP POLICY tenant_update ON "price_books";
--> statement-breakpoint
DROP POLICY tenant_delete ON "price_books";
--> statement-breakpoint
DROP POLICY platform_rows ON "price_books";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "audit_log";
--> statement-breakpoint
DROP POLICY platform_rows ON "audit_log";
--> statement-breakpoint
DROP POLICY tenant_isolation ON "events";
--> statement-breakpoint
DROP POLICY platform_rows ON "events";
--> statement-breakpoint
CREATE POLICY tenant_read ON "organizations" FOR SELECT USING ((id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) OR (id IN (SELECT m.org_id FROM "memberships" m WHERE m.user_id = (select nullif((select current_setting('app.user_id', true)), '')::uuid))));
--> statement-breakpoint
CREATE POLICY tenant_insert ON "organizations" FOR INSERT WITH CHECK (id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_update ON "organizations" FOR UPDATE USING (id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_delete ON "organizations" FOR DELETE USING (id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_read ON "memberships" FOR SELECT USING ((org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) OR (user_id = (select nullif((select current_setting('app.user_id', true)), '')::uuid)));
--> statement-breakpoint
CREATE POLICY tenant_insert ON "memberships" FOR INSERT WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_update ON "memberships" FOR UPDATE USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_delete ON "memberships" FOR DELETE USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_read ON "invitations" FOR SELECT USING ((org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) OR (lower(email) = (SELECT lower(u.email) FROM "users" u WHERE u.id = (select nullif((select current_setting('app.user_id', true)), '')::uuid))));
--> statement-breakpoint
CREATE POLICY tenant_insert ON "invitations" FOR INSERT WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_update ON "invitations" FOR UPDATE USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_delete ON "invitations" FOR DELETE USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "org_system_one_keys" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "agent_tokens" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "org_webhook_secrets" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "apps" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "app_tokens" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "app_opportunities" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "app_set_bindings" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "projects" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "goals" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "question_sets" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "question_set_versions" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "release_pointers" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "release_events" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "experiments" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "proposals" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "runs" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "run_feedback" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "review_items" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "datasets" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "dataset_cases" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "dataset_snapshots" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "eval_runs" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "eval_case_results" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "studio_sessions" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "studio_examples" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "question_daily" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "usage_daily" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "billing_accounts" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "entitlement_overrides" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "usage_events" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "approval_requests" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "idempotency_keys" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "jobs" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "webhook_endpoints" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "plugin_configs" USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_read ON "price_books" FOR SELECT TO bandwise_app USING ((org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) OR (org_id IS NULL));
--> statement-breakpoint
CREATE POLICY tenant_insert ON "price_books" FOR INSERT TO bandwise_app WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_update ON "price_books" FOR UPDATE TO bandwise_app USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY tenant_delete ON "price_books" FOR DELETE TO bandwise_app USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY platform_rows ON "price_books" TO bandwise_platform USING (org_id IS NULL) WITH CHECK (org_id IS NULL);
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "audit_log" TO bandwise_app USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY platform_rows ON "audit_log" TO bandwise_platform USING (org_id IS NULL) WITH CHECK (org_id IS NULL);
--> statement-breakpoint
CREATE POLICY tenant_isolation ON "events" TO bandwise_app USING (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid)) WITH CHECK (org_id = (select nullif((select current_setting('app.org_id', true)), '')::uuid));
--> statement-breakpoint
CREATE POLICY platform_rows ON "events" TO bandwise_platform USING (org_id IS NULL) WITH CHECK (org_id IS NULL);
-- bandwise:policy-block:end
