// Closed unions for text columns. Where @sysone/core has the zod enum, the column reuses its
// options, so the database type and the contract cannot drift. Unions data-model.md names that
// have no contract enum are listed here.

import {
  AgentClient,
  ActorType,
  ApprovalStatus,
  AppLanguage,
  Band,
  BindingRuntime,
  Channel,
  Client,
  CounterfactualMode,
  CurrentApproach,
  DeployTarget,
  ExperimentArm,
  ExperimentKind,
  FeedbackSource,
  JobStatus,
  KeyMode,
  ModelKind,
  ModelStatus,
  OpportunitySource,
  OpportunityStatus,
  Pattern,
  PiiMode,
  PlatformRole,
  PointerChannel,
  ProposalKind,
  ReleaseKind,
  ReviewItemKind,
  ReviewItemReason,
  ReviewItemStatus,
  Role,
  RolloutStage,
  RunRecordSource,
  RunStatus,
  SavingsKind,
  SavingsSuppressed,
  StorageMode,
  SystemOneProvider,
  VersionSource,
  VersionStatus,
  Action,
} from "@sysone/core/contracts";

/** A zod enum's options as the non-empty tuple drizzle's text({ enum }) wants. */
function options<T extends string>(e: { readonly options: readonly T[] }): [T, ...T[]] {
  const [first, ...rest] = e.options;
  if (first === undefined) throw new Error("enum has no options");
  return [first, ...rest];
}

export const E = {
  role: options(Role),
  platformRole: options(PlatformRole),
  client: options(Client),
  agentClient: options(AgentClient),
  actorType: options(ActorType),
  band: options(Band),
  action: options(Action),
  channel: options(Channel),
  pointerChannel: options(PointerChannel),
  rolloutStage: options(RolloutStage),
  releaseKind: options(ReleaseKind),
  experimentArm: options(ExperimentArm),
  experimentKind: options(ExperimentKind),
  proposalKind: options(ProposalKind),
  savingsKind: options(SavingsKind),
  savingsSuppressed: options(SavingsSuppressed),
  counterfactualMode: options(CounterfactualMode),
  piiMode: options(PiiMode),
  storageMode: options(StorageMode),
  keyMode: options(KeyMode),
  provider: options(SystemOneProvider),
  runSource: options(RunRecordSource),
  runStatus: options(RunStatus),
  versionStatus: options(VersionStatus),
  versionSource: options(VersionSource),
  reviewKind: options(ReviewItemKind),
  reviewReason: options(ReviewItemReason),
  reviewStatus: options(ReviewItemStatus),
  approvalStatus: options(ApprovalStatus),
  feedbackSource: options(FeedbackSource),
  jobStatus: options(JobStatus),
  modelKind: options(ModelKind),
  modelStatus: options(ModelStatus),
  appLanguage: options(AppLanguage),
  deployTarget: options(DeployTarget),
  bindingRuntime: options(BindingRuntime),
  opportunitySource: options(OpportunitySource),
  opportunityStatus: options(OpportunityStatus),
  currentApproach: options(CurrentApproach),
  pattern: options(Pattern),
  // Unions from data-model.md without a contract enum.
  orgStatus: ["active", "suspended", "deleted"],
  keyStatus: ["active", "invalid", "revoked"],
  appTokenKind: ["secret", "publishable"],
  appTokenPrefix: ["sk_live_", "sk_test_", "pk_live_"],
  deviceCodeStatus: ["pending", "approved", "denied", "used"],
  deviceClient: ["cli", "mcp", "extension"],
  experimentStatus: ["running", "promoted", "stopped"],
  proposalStatus: ["open", "accepted", "rejected", "expired"],
  proposalCreatedBy: ["system", "user", "agent"],
  datasetCaseSource: ["manual", "review", "import", "studio", "production"],
  datasetLabelSource: ["reviewer", "app", "studio", "import", "agent"],
  split: ["drafting", "calibration", "test"],
  studioLabelSource: ["human", "agent", "review"],
  // ADR-006: usage_events kinds and push status.
  usageKind: ["run", "eval_run", "system_one_cost", "llm_cost"],
  pushStatus: ["pending", "sent", "skipped"],
} as const;
